const MAP: Record<string, string> = {
  US: "美国",
  JP: "日本",
  DE: "德国",
  GB: "英国",
  FR: "法国",
  CA: "加拿大",
  AU: "澳大利亚",
  SG: "新加坡",
  KR: "韩国",
  IN: "印度",
  BR: "巴西",
  RU: "俄罗斯",
  TR: "土耳其",
  ES: "西班牙",
  IT: "意大利",
  MX: "墨西哥",
  ID: "印度尼西亚",
  TH: "泰国",
  VN: "越南",
  PH: "菲律宾",
  MY: "马来西亚",
  SA: "沙特阿拉伯",
  AE: "阿联酋",
  NL: "荷兰",
  CH: "瑞士",
  SE: "瑞典",
  NO: "挪威",
  PL: "波兰",
  UA: "乌克兰",
  AR: "阿根廷",
  CL: "智利",
  ZA: "南非",
  NG: "尼日利亚",
  EG: "埃及",
  HK: "中国香港",
  MO: "中国澳门",
  TW: "中国台湾",
  CN: "中国大陆",
  ZZ: "未知地区"
};

export function countryZh(code: string): string {
  const c = (code || "ZZ").toUpperCase();
  return MAP[c] ?? c;
}
